### ISSUE TITLE
Uncaught TypeError: Cannot read property 'focus' of undefined

### ISSUE THREAD

**Issue by bnb** [sdinesh86/template-generator#4]
[Enter steps to reproduce below:]

1. Add Group
2. Add two pages
3. Add variables in those two pages (using underscores in names)
4. Generate these templates
5. Error

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [template-generator](https://github.com/sdinesh86/template-generator) package, v0.12.0

### Stack Trace

Uncaught TypeError: Cannot read property 'focus' of undefined

```
At /Users/tier/.atom/packages/template-generator/lib/template-generator-fields-list.coffee:112

TypeError: Cannot read property 'focus' of undefined
    at FieldsListView.module.exports.FieldsListView.populateFields (/Users/tier/.atom/packages/template-generator/lib/template-generator-fields-list.coffee:112:44)
    at FieldsListView.module.exports.FieldsListView.attach (/Users/tier/.atom/packages/template-generator/lib/template-generator-fields-list.coffee:120:6)
    at TemplateSelectorListView.module.exports.TemplateSelectorListView.confirmed (/Users/tier/.atom/packages/template-generator/lib/template-generator-template-selector-dialog.coffee:56:24)
    at TemplateSelectorListView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-li.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
    at HTMLOListElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLOListElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:48 core:save (atom-text-editor.editor.is-focused)
  3x -2:05.8.0 markdown:emphasis (atom-text-editor.editor.is-focused)
     -1:55.9.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -1:54.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:51.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:50.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:49.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:45.5.0 markdown:emphasis (atom-text-editor.editor.is-focused)
  5x -1:45 core:move-right (atom-text-editor.editor.is-focused)
  6x -1:42.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:41.1.0 markdown:emphasis (atom-text-editor.editor.is-focused)
     -1:32.4.0 core:save (atom-text-editor.editor.is-focused)
  6x -1:04.6.0 markdown:emphasis (atom-text-editor.editor.is-focused)
  5x -0:26.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:24.9.0 markdown:emphasis (atom-text-editor.editor.is-focused)
     -0:06.7.0 template-generator:toggle-template-generator (span.name.icon.icon-file-directory)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "language-gfm",
      "language-gfm",
      "language-gfm",
      "language-gfm",
      "language-gfm",
      "language-gfm"
    ]
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.4.1
emmet, v2.4.3
language-markdown, v0.13.0
merge-conflicts, v1.4.2
minimap, v4.23.5
pigments, v0.26.2
project-manager, v2.9.7
template-generator, v0.12.0

# Dev
No dev packages
```

**Comment by sdinesh86** [comment]
@bnb Issue is fixed you can get the latest version now
